services: 
  fastapi:
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    image: image-fastapi
    container_name: fastapi-application
    restart: always

    depends_on:
      postgresDB:
        condition: service_healthy

    #puerto-expuesto-local : puerto-expuesto-contenedor-app
    ports:
      - '${PORT_LOCAL}:${PORT_REMOTE}'
    
    #Sincronizacion del código local con el contenedor
    volumes:
     - .:/app/

    #SINCRONIZACION LIMPIA CON EL ARCHIVO .ENV
    env_file:
      - .env

  postgresDB:
    image: postgres:15-alpine
    container_name: ${POSTGRES_DB}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - posgrest-data:/var/lib/postgresql/data

volumes:
  posgrest-data:
    external: false