services: 
  fastapi:
    image: image-fastapi
    build: .
    container_name: fastap-application

    #puerto-expuesto-local : puerto-expuesto-contenedor-app
    ports:
      - '8085:8000'
    
    #Sincronizacion del código local con el contenedor
    volumes:
     - .:/app